In [1]:
import pandas as pd

In [5]:
df = pd.read_csv("Sample - Superstore.csv", encoding="latin1")

In [6]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4578 entries, 0 to 4577
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         4578 non-null   int64
 1   Order ID       4578 non-null   str
 2   Order Date     4578 non-null   str
 3   Ship Date      4578 non-null   str
 4   Ship Mode      4578 non-null   str
 5   Customer ID    4578 non-null   str
 6   Customer Name  4578 non-null   str
 7   Segment        4578 non-null   str
 8   Country        4578 non-null   str
 9   City           4578 non-null   str
 10  State          4578 non-null   str
 11  Postal Code    4578 non-null   int64
 12  Region         4578 non-null   str
 13  Product ID     4578 non-null   str
 14  Category       4578 non-null   str
 15  Sub-Category   4578 non-null   str
 16  Product Name   4578 non-null   str
 17  Sales          4578 non-null   float64
 18  Quantity       4578 non-null   int64
 19  Discount       4578 non-null   float64
 20  Profit         4578 non-null   float64
dtypes: float64(3), int64(3), str(15)
memory usage: 751.2 KB

In [8]:
df.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,4578.000000,4578.000000,4578.000000,4578.000000,4578.000000,4578.000000
mean,2289.500000,54879.289646,232.425959,3.802315,0.156686,26.212476
std,1321.699096,31767.037835,650.125232,2.245579,0.206231,211.017604
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-3839.990400
25%,1145.250000,22920.750000,16.768000,2.000000,0.000000,1.747800
50%,2289.500000,55122.000000,52.728000,3.000000,0.200000,8.713900
75%,3433.750000,90004.000000,213.394000,5.000000,0.200000,28.847950
max,4578.000000,99207.000000,22638.480000,14.000000,0.800000,5039.985600

In [9]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.rename(columns={"Order Date":"Order_Date","Ship Date":"Ship_Date"}, inplace= True)

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4578 entries, 0 to 4577
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         4578 non-null   int64
 1   Order ID       4578 non-null   str
 2   Order_Date     4578 non-null   str
 3   Ship_Date      4578 non-null   str
 4   Ship Mode      4578 non-null   str
 5   Customer ID    4578 non-null   str
 6   Customer Name  4578 non-null   str
 7   Segment        4578 non-null   str
 8   Country        4578 non-null   str
 9   City           4578 non-null   str
 10  State          4578 non-null   str
 11  Postal Code    4578 non-null   int64
 12  Region         4578 non-null   str
 13  Product ID     4578 non-null   str
 14  Category       4578 non-null   str
 15  Sub-Category   4578 non-null   str
 16  Product Name   4578 non-null   str
 17  Sales          4578 non-null   float64
 18  Quantity       4578 non-null   int64
 19  Discount       4578 non-null   float64
 20  Profit         4578 non-null   float64
dtypes: float64(3), int64(3), str(15)
memory usage: 751.2 KB

In [15]:
df["Order_Date"]=pd.to_datetime(df["Order_Date"])
df["Ship_Date"]=pd.to_datetime(df["Ship_Date"])

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4578 entries, 0 to 4577
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         4578 non-null   int64
 1   Order ID       4578 non-null   str
 2   Order_Date     4578 non-null   datetime64[us]
 3   Ship_Date      4578 non-null   datetime64[us]
 4   Ship Mode      4578 non-null   str
 5   Customer ID    4578 non-null   str
 6   Customer Name  4578 non-null   str
 7   Segment        4578 non-null   str
 8   Country        4578 non-null   str
 9   City           4578 non-null   str
 10  State          4578 non-null   str
 11  Postal Code    4578 non-null   int64
 12  Region         4578 non-null   str
 13  Product ID     4578 non-null   str
 14  Category       4578 non-null   str
 15  Sub-Category   4578 non-null   str
 16  Product Name   4578 non-null   str
 17  Sales          4578 non-null   float64
 18  Quantity       4578 non-null   int64
 19  Discount       4578 non-null   float64
 20  Profit         4578 non-null   float64
dtypes: datetime64[us](2), float64(3), int64(3), str(13)
memory usage: 751.2 KB

In [18]:
df.columns=["row_id",
           "order_id",
           "order_date",
           "ship_date",
           "ship_mode",
           "customer_id",
           "customer_name",
           "segment",
           "country",
           "city",
           "state",
           "postal_code",
           "region",
           "product_id",
           "category",
           "sub_category",
           "product_name",
           "sales",
           "quantity",
           "discount",
           "profit"]

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4578 entries, 0 to 4577
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   row_id         4578 non-null   int64
 1   order_id       4578 non-null   str
 2   order_date     4578 non-null   datetime64[us]
 3   ship_date      4578 non-null   datetime64[us]
 4   ship_mode      4578 non-null   str
 5   customer_id    4578 non-null   str
 6   customer_name  4578 non-null   str
 7   segment        4578 non-null   str
 8   country        4578 non-null   str
 9   city           4578 non-null   str
 10  state          4578 non-null   str
 11  postal_code    4578 non-null   int64
 12  region         4578 non-null   str
 13  product_id     4578 non-null   str
 14  category       4578 non-null   str
 15  sub_category   4578 non-null   str
 16  product_name   4578 non-null   str
 17  sales          4578 non-null   float64
 18  quantity       4578 non-null   int64
 19  discount       4578 non-null   float64
 20  profit         4578 non-null   float64
dtypes: datetime64[us](2), float64(3), int64(3), str(13)
memory usage: 751.2 KB

In [22]:
object_columns = df.select_dtypes(include="str").columns
for col in object_columns:
    if(df[col]!=df[col].str.strip()).any():
        print(col)

product_name

In [24]:
df["product_name"]=df["product_name"].str.strip()

In [25]:
for col in object_columns:
    print(f"\n Column: {col}")
    print(df[col].unique()[:10])

 Column: order_id
<StringArray>
['CA-2016-152156', 'CA-2016-138688', 'US-2015-108966', 'CA-2014-115812',
 'CA-2017-114412', 'CA-2016-161389', 'US-2015-118983', 'CA-2014-105893',
 'CA-2014-167164', 'CA-2014-143336']
Length: 10, dtype: str

 Column: ship_mode
<StringArray>
['Second Class', 'Standard Class', 'First Class', 'Same Day']
Length: 4, dtype: str

 Column: customer_id
<StringArray>
['CG-12520', 'DV-13045', 'SO-20335', 'BH-11710', 'AA-10480', 'IM-15070',
 'HP-14815', 'PK-19075', 'AG-10270', 'ZD-21925']
Length: 10, dtype: str

 Column: customer_name
<StringArray>
[       'Claire Gute',    'Darrin Van Huff',     'Sean O'Donnell',
    'Brosina Hoffman',       'Andrew Allen',       'Irene Maddox',
      'Harold Pawlan',          'Pete Kriz',    'Alejandro Grove',
 'Zuschuss Donatelli']
Length: 10, dtype: str

 Column: segment
<StringArray>
['Consumer', 'Corporate', 'Home Office']
Length: 3, dtype: str

 Column: country
<StringArray>
['United States']
Length: 1, dtype: str

 Column: city
<StringArray>
[      'Henderson',     'Los Angeles', 'Fort Lauderdale',         'Concord',
         'Seattle',      'Fort Worth',         'Madison',     'West Jordan',
   'San Francisco',         'Fremont']
Length: 10, dtype: str

 Column: state
<StringArray>
[      'Kentucky',     'California',        'Florida', 'North Carolina',
     'Washington',          'Texas',      'Wisconsin',           'Utah',
       'Nebraska',   'Pennsylvania']
Length: 10, dtype: str

 Column: region
<StringArray>
['South', 'West', 'Central', 'East']
Length: 4, dtype: str

 Column: product_id
<StringArray>
['FUR-BO-10001798', 'FUR-CH-10000454', 'OFF-LA-10000240', 'FUR-TA-10000577',
 'OFF-ST-10000760', 'FUR-FU-10001487', 'OFF-AR-10002833', 'TEC-PH-10002275',
 'OFF-BI-10003910', 'OFF-AP-10002892']
Length: 10, dtype: str

 Column: category
<StringArray>
['Furniture', 'Office Supplies', 'Technology']
Length: 3, dtype: str

 Column: sub_category
<StringArray>
[  'Bookcases',      'Chairs',      'Labels',      'Tables',     'Storage',
 'Furnishings',         'Art',      'Phones',     'Binders',  'Appliances']
Length: 10, dtype: str

 Column: product_name
<StringArray>
[                               'Bush Somerset Collection Bookcase',
      'Hon Deluxe Fabric Upholstered Stacking Chairs, Rounded Back',
        'Self-Adhesive Address Labels for Typewriters by Universal',
                    'Bretford CR4500 Series Slim Rectangular Table',
                                   'Eldon Fold 'N Roll Cart System',
 'Eldon Expressions Wood and Plastic Desk Accessories, Cherry Wood',
                                                       'Newell 322',
                                   'Mitel 5320 IP Phone VoIP phone',
             'DXL Angle-View Binders with Locking Rings by Samsill',
                                 'Belkin F5C206VTEL 6 Outlet Surge']
Length: 10, dtype: str

In [26]:
df[df["sales"]<0]

Empty DataFrame
Columns: [row_id, order_id, order_date, ship_date, ship_mode, customer_id, customer_name, segment, country, city, state, postal_code, region, product_id, category, sub_category, product_name, sales, quantity, discount, profit]
Index: []

[0 rows x 21 columns]

In [29]:
df[(df["discount"]<0)|(df["discount"]>1)]

Empty DataFrame
Columns: [row_id, order_id, order_date, ship_date, ship_mode, customer_id, customer_name, segment, country, city, state, postal_code, region, product_id, category, sub_category, product_name, sales, quantity, discount, profit]
Index: []

[0 rows x 21 columns]

In [30]:
df[["sales","profit","discount","quantity"]].describe()

              sales       profit     discount     quantity
count   4578.000000  4578.000000  4578.000000  4578.000000
mean     232.425959    26.212476     0.156686     3.802315
std      650.125232   211.017604     0.206231     2.245579
min        0.444000 -3839.990400     0.000000     1.000000
25%       16.768000     1.747800     0.000000     2.000000
50%       52.728000     8.713900     0.200000     3.000000
75%      213.394000    28.847950     0.200000     5.000000
max    22638.480000  5039.985600     0.800000    14.000000

In [31]:
(df["ship_date"]<df["order_date"]).sum()

np.int64(0)

In [32]:
df.to_csv("cleaned_superstore.csv",index=False)